version: '3.0'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./php/etc/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "127.0.0.1:8443:80"
      - "127.0.0.1:8080:80"
    depends_on:
      - webapp

  webapp:
    cpus: 2
    mem_limit: 4g
    build:
      context: ../webapp/php
    init: true
    working_dir: /home/isucon/webapp/php
    container_name: webapp
    volumes:
      - ./php/usr/local/etc/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ../webapp/sql:/home/isucon/webapp/sql
      - ../webapp/pdns:/home/isucon/webapp/pdns
      - ../provisioning/ansible/roles/powerdns/files/pdns.conf:/etc/powerdns/pdns.conf:ro
      - ../provisioning/ansible/roles/powerdns/files/pdns.d/docker.conf:/etc/powerdns/pdns.d/docker.conf:ro
      - ../webapp/img:/home/isucon/webapp/img
    environment:
      ISUCON13_MYSQL_DIALCONFIG_ADDRESS: mysql
      ISUCON13_POWERDNS_HOST: powerdns
      ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS: 127.0.0.1
      ISUCON13_POWERDNS_DISABLED: true
    depends_on:
      mysql:
        condition: service_healthy
